name: Deploy Pygame to GitHub Pages

on:
  push:
    branches: [ main ]

# GRANT WRITE PERMISSIONS TO GITHUB ACTIONS BOT
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pygbag
        run: pip install pygbag

      - name: Build WebAssembly App
        run: python3 -m pygbag --build main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
